sudo: required
dist: trusty

language: java

jdk:
  - openjdk11

services:
  - docker

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose -f docker_local/docker-compose.yml -p kotlin pull
  - docker-compose -f docker_local/docker-compose.yml -p kotlin up --build -d

script:
  - ./gradlew clean build

after_script:
  - docker-compose -f docker_local/docker-compose.yml -p kotlin down -v