sudo: required
dist: trusty

language: java

jdk:
  - openjdk11

services:
  - docker

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y chromium-browser
  - sudo apt-get -qq install -y chromium-chromedriver

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose -f docker_local/docker-compose.yml -p kotlin_project pull
  - docker-compose -f docker_local/docker-compose.yml -p kotlin_project up --build -d

script:
  - ./gradlew clean build -DchromeDriverBinary=/usr/lib/chromium-browser/chromedriver -DchromeBinary=/usr/bin/chromium-browser -DchromeHeadless=true
  - ./minify-js-css.sh
  - ./gradlew clean build -Dapp.development.mode=false -DchromeDriverBinary=/usr/lib/chromium-browser/chromedriver -DchromeBinary=/usr/bin/chromium-browser -DchromeHeadless=true

after_script:
  - docker-compose -f docker_local/docker-compose.yml -p kotlin_project down -v