sudo: required
dist: trusty

language: java

jdk:
  - openjdk11

addons:
  chrome: stable

services:
  - docker

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y chromium-chromedriver

before_script:
  - docker --version
  - docker-compose --version
  - ./gradlew pullDocker --info
  - ./gradlew startDocker --info

script:
  - ./gradlew clean minifyFiles assemble
  - ./gradlew build --info -DchromeDriverBinary=/usr/lib/chromium-browser/chromedriver -DchromeHeadless=true
  - ./gradlew build --info -Dapp.development.mode=false -DchromeDriverBinary=/usr/lib/chromium-browser/chromedriver -DchromeHeadless=true

after_script:
  - ./gradlew stopDocker --info