version: '3'
networks:
  main_network:

services:
  ktor-jdbi-postgres:
    container_name: ktor-jdbi-postgres
    image: "postgres:11-alpine"
    ports:
      - "25432:5432"
    environment:
      - "POSTGRES_USER=myuser"
      - "POSTGRES_PASSWORD=superpassword"
    networks:
      main_network:
        aliases:
          - ktor-jdbi-postgres

  wiremock:
    container_name: wiremock
    build: ./wiremock
    ports:
      - "18089:8089"
    networks:
      main_network:
        aliases:
          - wiremock

  ktor-application:
    container_name: ktor-application
    build: ./ktor-application
    depends_on:
      - ktor-jdbi-postgres
      - wiremock
    ports:
      - "18080:18080"
    environment:
      - "PORT=18080"
      - "JS_CONFIG_PROFILE=local_docker"
      - "APP_DEVELOPMENT_MODE=true"
      - "JDBC_URL=jdbc:postgresql://ktor-jdbi-postgres:5432/myuser"
      - "JDBC_USERNAME=myuser"
      - "JDBC_PASSWORD=superpassword"
      - "CUSTOMER_SERVICE_BASE_URL=http://wiremock:8089"
    networks:
      main_network:
        aliases:
          - ktor-application