name: 'CI-master'

on:
  push:
    branches:
      - master
    tags:
      - v1
  schedule:
    - cron:  '0 11 * * *'

jobs:
  master-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Java 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Cache gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-cache-master-v1
        restore-keys: |
          ${{ runner.os }}-gradle-cache-master-v1
    - name: 'Install dependencies'
      run: |
        ./ci-install-dependencies.sh
    - name: 'CI Build Command'
      run: |
        ./ci-build.sh
    - name: Archive integration test results
      uses: actions/upload-artifact@v1
      with:
        name: ktor-integration-test-result
        path: ktor-integration-test/build/reports/tests
    - name: Archive integration test results
      uses: actions/upload-artifact@v1
      with:
        name: ktor-dependency-license
        path: ktor/build/reports/dependency-license