name: 'CI-master'

on:
  repository_dispatch:
    types: do-master-ci
  push:
    branches:
      - master
    tags:
      - v1
  schedule:
    - cron:  '0 17 * * *' # runs on every day at 5pm UTC

jobs:
  master-build:
    runs-on: ubuntu-latest
    timeout-minutes: 420 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: '1'
    - name: Install Java 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: 'Print event data'
      run: |
        echo "TransactionId: $TRANSACTION_ID"
      env:
        TRANSACTION_ID: ${{ github.event.client_payload.transaction_id }}
    - name: Cache gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-cache-master-v1
        restore-keys: |
          ${{ runner.os }}-gradle-cache-master-v1
    - name: 'Print environment variables'
      run: |
        ./print-env-vars.sh
      env:
        CUSTOM_VARIABLE: 'Test 123'
        ENCRYPTED_VARIABLE: ${{ secrets.EncryptedVariable }}
    - name: 'Install dependencies'
      run: |
        ./ci-install-dependencies.sh
    - name: 'CI Build Command'
      timeout-minutes: 20
      run: |
        ./ci-build.sh
    - name: Archive integration test results
      uses: actions/upload-artifact@v1
      with:
        name: ktor-integration-test-result
        path: ktor-integration-test/build/reports/tests
    - name: Archive dependencies license
      uses: actions/upload-artifact@v1
      with:
        name: ktor-dependency-license
        path: ktor/build/reports/dependency-license