name: 'CI-prod'

on:
  push:
    tags:
      - prod

jobs:
  prod-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Java 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Cache gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-cache-prod-v1
        restore-keys: |
          ${{ runner.os }}-gradle-cache-prod-v1
    - name: 'Install dependencies'
      run: |
        ./ci-install-dependencies.sh
    - name: 'CI Build Command'
      run: |
        ./ci-build.sh
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ktor-exec
        path: ktor/build/libs/ktor-exec.jar
    - name: Archive integration test results
      uses: actions/upload-artifact@v1
      with:
        name: ktor-integration-test-result
        path: ktor-integration-test/build/reports/tests