name: CI

on: [push]

jobs:
  my-first-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: Run a multi-line script
      run: |
        ./gradlew clean assemble